exclude_paths:
- ".meteor/*"
engines:
  duplication:
    enabled: true
    config:
      languages:
        - javascript
  eslint:
    enabled: false
  csslint:
    enabled: true
  fixme:
    enabled: true
ratings:
   paths:
   - "**.js"
   - "**.jsx"
   - "**.css"
