# @todo: Write coments about what this file is for
# Usage:
# docker-compose up -d

reaction:
  image: reactioncommerce/reaction:latest
  links:
    - mongo
  ports:
    - "3000:3000"
  environment:
    ROOT_URL: "http://localhost"
    MONGO_URL: "mongodb://mongo:27017/reaction"

mongo:
  image: mongo:3.6
  command: mongod --bind_ip_all
