# @todo: Write coments about what this file is for
# Usage:
# docker-compose up -d

version: '3.4'

services:
  reaction:
    build:
      context: .
      target: meteor-dev
    command: "reaction"
    depends_on:
      - mongo
    environment:
      ROOT_URL: "http://localhost"
      MONGO_URL: "mongodb://mongo:27017/reaction"
    ports:
      - "3000:3000"

  mongo:
    image: mongo:3.6
    command: mongod --bind_ip_all

