# This docker-compose file is used to run the devserver (non-Meteor) app
# Usage: docker-compose -f docker-compose-devserver.yml up [-d]

version: '3.4'

services:
  devserver:
    build:
      context: .
      dockerfile: Dockerfile-devserver
    command: ["npm", "run", "devserver"]
    depends_on:
      - mongo
    environment:
      ROOT_URL: "http://localhost:3030"
      MONGO_URL: "mongodb://mongo:27017/reaction"
    ports:
      - "3030:3030"
    volumes:
      - .:/app
      - devserver_node_modules:/app/node_modules # do not link node_modules in, and persist it between dc up runs

  mongo:
    image: mongo:3.4
    command: mongod --storageEngine=wiredTiger
    ports:
      - "27017:27017"
    volumes:
      - mongo-db:/data/db

volumes:
  devserver_node_modules:
  mongo-db:
