version: 2

# The following stanza defines a map named defaults with a variable that may be
# inserted using the YAML merge (<<: *) key later in the file to save some
# typing. See http://yaml.org/type/merge.html for details.
defaults: &defaults
  environment:
    CI_SCRIPTS: 'npx --quiet --package @reactioncommerce/ci-scripts@1.6.2'
    DOCKER_REPOSITORY: "reactioncommerce/reaction"
    DOCKER_NAMESPACE: "reactioncommerce"
    DOCKER_NAME: "reaction"
  docker:
    - image: circleci/node:12.14.1-stretch

jobs:
  install-dependencies:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - reaction-v3-node-modules-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}
            - reaction-v3-node-modules-{{ .Branch }}
      - run:
          name: Install NPM dependencies
          command: npm ci
      - save_cache:
          key: reaction-v3-node-modules-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - save_cache:
          key: reaction-v3-node-modules-{{ .Branch }}
          paths:
            - node_modules

  dockerfile-lint:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Lint Dockerfiles
          command: ${CI_SCRIPTS} lint-dockerfiles

  eslint:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - reaction-v3-node-modules-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}
            - reaction-v3-node-modules-{{ .Branch }}
      - run:
          name: Lint JavaScript
          command: npm run lint

  graphql-lint:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - reaction-v3-node-modules-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}
            - reaction-v3-node-modules-{{ .Branch }}
      - run:
          name: Lint GraphQL schemas
          command: npm run lint:gql

  test-unit:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - reaction-v3-node-modules-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}
            - reaction-v3-node-modules-{{ .Branch }}
      - run:
          name: Run Unit Tests
          command: npm run test:unit

  test-integration-query:
    <<: *defaults
    docker:
      - image: circleci/node:12.14.1-stretch
      # Integration tests need MongoDB server running and accessible on port 27017
      - image: circleci/mongo:4.2.0
        command: mongod --oplogSize 128 --replSet rs0 --storageEngine=wiredTiger
        ports:
          - "27017:27017"
    steps:
      - checkout
      - restore_cache:
          keys:
            - reaction-v3-node-modules-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}
            - reaction-v3-node-modules-{{ .Branch }}
      - run:
          name: Run Integration Query Tests
          command: MONGO_URL=mongodb://localhost:27017/test npm run test:integration:query

  test-integration-mutation:
    <<: *defaults
    docker:
      - image: circleci/node:12.14.1-stretch
      # Integration tests need MongoDB server running and accessible on port 27017
      - image: circleci/mongo:4.2.0
        command: mongod --oplogSize 128 --replSet rs0 --storageEngine=wiredTiger
        ports:
          - "27017:27017"
    steps:
      - checkout
      - restore_cache:
          keys:
            - reaction-v3-node-modules-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}
            - reaction-v3-node-modules-{{ .Branch }}
      - run:
          name: Run Integration Mutation Tests
          command: MONGO_URL=mongodb://localhost:27017/test npm run test:integration:mutation


  docker-build-push:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build and push production Docker image
          command: ${CI_SCRIPTS} docker-build-tag-push . ${DOCKER_REPOSITORY}

  deploy-docs:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install AWS CLI
          command: sudo apt-get -y -qq install awscli
      - run:
          name: NPM Install JSDoc
          command: sudo npm install -g jsdoc
      - run:
          name: Build JSDoc files
          command: |
            jsdoc . \
              --verbose \
              --configure .reaction/jsdoc/jsdoc.json \
              --readme .reaction/jsdoc/templates/static/README.md
      - run:
          name: Deploy Doc files to S3
          command: |
            if [[ "${API_DOC_BUCKET}" && "${API_DOC_BUCKET_REGION}" ]]; then
              aws s3 sync /tmp/reaction-docs ${API_DOC_BUCKET} --delete --region ${API_DOC_BUCKET_REGION}
            else
              echo "S3 bucket configuration not found for jsdocs"
              echo "Set API_DOC_BUCKET and API_DOC_BUCKET_REGION to build and deploy jsdocs to S3"
              exit 1;
            fi

workflows:
  version: 2
  build_and_test:
    jobs:
      - install-dependencies
      - dockerfile-lint:
          requires:
            - install-dependencies
      - eslint:
          requires:
            - install-dependencies
      - graphql-lint:
          requires:
            - install-dependencies
      - test-unit:
          requires:
            - install-dependencies
      - test-integration-query:
          requires:
            - install-dependencies
      - test-integration-mutation:
          requires:
            - install-dependencies
      - docker-build-push:
          context: reaction-publish-docker
          requires:
            - dockerfile-lint
            - eslint
            - graphql-lint
            - test-unit
            - test-integration-query
            - test-integration-mutation
      - deploy-docs:
          requires:
            - dockerfile-lint
            - eslint
            - graphql-lint
            - test-unit
            - test-integration-query
            - test-integration-mutation
          filters:
            branches:
              only: /^master$/
