# This CircleCI configuration uses workflows to fan-out to multiple jobs.  The
# workflow is Dockerized. The first job builds the Docker image which is used
# in all future steps.
#
#  Assumes that the Docker image is published to Docker Hub.


version: 2

# The following stanza defines a map named defaults with a variable that may be
# inserted using the YAML merge (<<: *) key later in the file to save some
# typing. See http://yaml.org/type/merge.html for details.
defaults: &defaults
  environment:
    - DOCKER_REPOSITORY: "reactioncommerce/reaction"
    - DOCKER_NAMESPACE: "reactioncommerce"
    - DOCKER_NAME: "reaction"
    - TOOL_NODE_FLAGS: "--max-old-space-size=4096"
  working_directory: ~/reaction-app
  docker:
    - image: circleci/node:8-stretch

jobs:
  docker-test-build:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: docker-cache
      - run:
          name: Build Meteor-Dev Stage
          command: |
            docker build --target meteor-dev \
              -t "$DOCKER_REPOSITORY:$CIRCLE_SHA1-dev" .
            mkdir -p docker-cache
            docker save \
              -o docker-cache/docker-dev-image.tar \
              "$DOCKER_REPOSITORY:$CIRCLE_SHA1-dev"
      - persist_to_workspace:
          root: docker-cache
          paths:
            - docker-dev-image.tar

  docker-build:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: docker-cache
      - run:
          name: Discover Docker Tags
          command: |
            mkdir -p docker-cache
            SHA1=$(git rev-parse --verify "${CIRCLE_SHA1}")
            .circleci/bin/docker-tags "$SHA1" "$CIRCLE_BRANCH" | sed 's/\//-/g' | xargs -t -I % \
              > docker-cache/docker-tags.txt
      - run:
          name: Docker build
          command: |
            docker build \
              --build-arg TOOL_NODE_FLAGS="--max-old-space-size=4096" \
              -t "$DOCKER_REPOSITORY:$CIRCLE_SHA1" .
            mkdir -p docker-cache
            docker save \
              -o docker-cache/docker-image.tar \
              "$DOCKER_REPOSITORY:$CIRCLE_SHA1"
          no_output_timeout: 30m
      - persist_to_workspace:
          root: docker-cache
          paths:
            - docker-image.tar
            - docker-tags.txt

