environment:
  name: staging
  application:
    name: starterkit
    cluster: core
    services:
    - name: sk-core
      certificate_arn: arn:aws:acm:us-west-2:773713188930:certificate/c2979a7a-7b84-43ed-b3a7-24b0256a1b9f
      root_domain: staging.reactioncommerce.com
      dns_name: sample
      desired_task_count: 1
      min_task_count: 0
      max_task_count: 8
      min_healthy_percent: 100
      max_percent: 200
      alb_listener_port: 80
      alb_listener_path: /
      alb_listener_rule_priority: 1
      alb_health_check_path: /health
      task-definition:
        name: sk-core
        cpu: 500
        memory: 1800
        container:
          name: sk-core
          port: 3000
          override_image_from_circleci: true
          image: reactioncommerce/reaction
          #image_tag: 94f8e63365c03c7a67b6e626108cc30d11bd528a
          image_tag: 443896b4373cf444e6549e7fec50640c9a8a964d
          env_params:
          - name: REACTION_AUTH
          - name: REACTION_EMAIL
          - name: REACTION_USER
          - name: ROOT_URL
          - name: MONGO_URL
          - name: SKIP_FIXTURES
